import Icons from 'libraries/common/Icons';

class AmenityIcons {
    constructor() {
        this.list = {
            'Free Internet Available': 'internet',
            'Swimming Pool': 'pool',
            'Whirlpool': 'whirlpool',
            'Outdoor pool (seasonal)': 'pool',
            'Outdoor pool': 'pool',
            'Pool': 'pool',
            'Free Parking': 'parking',
            'Private parking': 'parking',
            'Parking': 'parking',
            'On-site parking': 'parking',
            'Secured parking': 'parking',
            'fitness center': 'gym',
            'Fitness Center or Spa': 'spa',
            'Spa and wellness centre': 'spa',
            'Massage': 'spa',
            'Spa': 'spa',
            'WiFi': 'wifi',
            'WiFi available in all areas': 'wifi',
            'WiFi everywhere': 'wifi',
            'Paid WiFi': 'wifi',
            'Restaurant': 'restaurant',
            'Air Conditioning': 'snow-flake',
            'Business Center': 'business-center',
            'Fax/photocopying': 'business-center',
            'Valet Parking': 'valet',
            'Internet Access': 'internet',
            'Internet services': 'internet',
            'Free High Speed Internet': 'internet',
            'Free Internet In Public Areas': 'internet',
            'Free Internet Access': 'internet',
            'Casino': 'casino',
            'Laundry': 'laundry',
            'Ironing service': 'laundry',
            'Trouser press': 'laundry',
            'Accessible': 'disabled',
            'Wheelchair accessible': 'disabled',
            'Accessible parking': 'disabled',
            'Accessible facilities': 'disabled',
            'Parking garage': 'parking',
            'Safety Deposit Box': 'safe',
            'Safe': 'safe',
            'Golf Course Nearby': 'sports-golf-course-nearby',
            'Golf Course': 'sports-golf-course-nearby',
            'Spa Services': 'spa',
            'Facilities for Disabled Guests': 'disabled',
            'Gift Shop / Shopping': 'gift',
            'Shops in Hotel': 'gift',
            'Gift shop': 'gift',
            'Souvenir/Gift Shop': 'gift',
            'Kids Club': 'kids-club',
            'Nightclub / Disco': 'discoball',
            'Designated Smoking Areas': 'smoking',
            'Express Check-In / Check-Out': 'checkout',
            'Medical Services': 'doctor',
            'On-site Live Performance': 'musician-icon',
            'Wake Up Service': 'alarm',
            'Smoke-Free Property': 'no-smoking',
            'Wheelchair Accessible': 'disabled',
            'Business Centre / Services': 'business-center',
            '24-Hour Front Desk': '24-hours',
            'ATM / Banking': 'atm',
            'ATM/cash machine on site': 'atm',
            'Elevator': 'elevator',
            'Room Service': 'room-service',
            'Dry cleaning': 'dry-cleaning',
            'Hot tub/jacuzzi': 'jacuzzi',
            'Hot tub': 'jacuzzi',
            'Newspapers': 'newspaper',
            'Snack bar': 'restaurant',
            'Car Rental Desk': 'car',
            'Car Rental': 'car',
            'Bar': 'drink',
            'Cocktail lounge': 'drink',
            'Cocktail lounge with entertainment': 'drink',
            'Cocktail lounge with light fare': 'drink',
            'Smoking area': 'smoking',
            'Meeting/Banquet Facilities': 'meeting',
            'Outdoor pool (all year)': 'pool',
            'Breakfast in the room': 'room-service',
            'Luggage storage': 'luggage-storage',
            'Pets Allowed': 'pet',
            'Express Check-In/Check-Out': 'check-out',
            'Private check-in/check-out': 'check-out',
            'Daily maid service': 'housekeeping',
            'Daily Housekeeping': 'housekeeping',
            'Concierge Service': 'concierge',
            'Evening entertainment': 'musician-icon',
            'Currency Exchange': 'currency-exchange',
            'Sauna': 'sauna',
            'Bicycle rental': 'sports-bicycles',
            'Barber/Beauty Shop': 'salon',
            'Nightclub/DJ': 'discoball',
            'Tennis Court': 'sports-tennis-courts',
            'Billiards': 'sports-pool-table',
            'Airport Shuttle': 'shuttle',
            'Private suite': 'private-suite',
            'Landmark view': 'landmark-view',
            'Ocean view': 'oceanview',
            'Mountain View': 'mountain-view',
            'City view': 'city-view',
            'Air conditioning': 'snow-flake',
            'Private Bathroom': 'bath',
            'Flat-screen TV': 'tv',
            Minibar: 'bar',
            'Free WiFi': 'wifi',
            Balcony: 'balcony',

        };
    }

    get(key) {
        // cant find key?
        if (this.list[key] === undefined) {
            return '/img/icons/icon-defs.svg#icon-circle-empty';
        }

        return `/img/icons/amenities-icon-defs.svg#icon-${this.list[key]}`;
    }
}

const amenityIcons = new AmenityIcons();
export default amenityIcons;
